### ISSUE TITLE
Add release configurations

### ISSUE THREAD

**Issue by crup** [xendora/react-timer#14]
Requirements:
- Fix/enhance rollup config - (currently borrowed from `create-react-library`) - Should support umd/cjs/ejs. Considering `kcd-scripts` for that which is already used in `downshift`
- Configure semantic-release with commitzen

**Comment by theashraf** [comment]
can I work on this one?

**Comment by crup** [comment]
Will go with `commitzen` and `semantic-release` for now. Let's discuss other options later.

**Comment by crup** [comment]
Added configurations #24
